### ISSUE TITLE
RuntimeError: arguments are located on different GPUs

### ISSUE THREAD

**Issue by Kwongrf** [czzbb/I3Net#1]
It seems like we can't train the model on multi-gpu.

```
Traceback (most recent call last):
  File "train_eval.py", line 896, in <module>
    train()
  File "train_eval.py", line 566, in train
    out, domain_g, domain_l, fea_lists, gcr_pre, global_feat, _ = net(images)
  File "/home/krf/anaconda3/envs/ssd3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/krf/anaconda3/envs/ssd3/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 152, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/krf/anaconda3/envs/ssd3/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 162, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/krf/anaconda3/envs/ssd3/lib/python3.8/site-packages/torch/nn/parallel/parallel_apply.py", line 85, in parallel_apply
    output.reraise()
  File "/home/krf/anaconda3/envs/ssd3/lib/python3.8/site-packages/torch/_utils.py", line 394, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in replica 1 on device 1.
Original Traceback (most recent call last):
  File "/home/krf/anaconda3/envs/ssd3/lib/python3.8/site-packages/torch/nn/parallel/parallel_apply.py", line 60, in _worker
    output = module(*input, **kwargs)
  File "/home/krf/anaconda3/envs/ssd3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/krf/models/I3Net/ssd_I3N.py", line 266, in forward
    g_feat = self.get_feature_vector(feat1, feat2.detach())
  File "/home/krf/models/I3Net/ssd_I3N.py", line 338, in get_feature_vector
    feat = self.RandomLayer([f1, f2])
  File "/home/krf/anaconda3/envs/ssd3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/krf/models/I3Net/ssd_I3N.py", line 136, in forward
    return_list = [torch.mm(input_list[i], self.random_matrix[i]) for i in range(self.input_num)]
  File "/home/krf/models/I3Net/ssd_I3N.py", line 136, in <listcomp>
    return_list = [torch.mm(input_list[i], self.random_matrix[i]) for i in range(self.input_num)]
RuntimeError: arguments are located on different GPUs at /opt/conda/conda-bld/pytorch_1579022027550/work/aten/src/THC/generic/THCTensorMathBlas.cu:277

```

**Comment by czzbb** [comment]
This code only supports a single GPU.
